# Generated by Django 2.2.28 on 2024-05-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240522_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hi',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
